version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - my-net
    env_file: 
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
      - cache
    build: ./
    restart: unless-stopped
    env_file: 
      - ./.env
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_NAME=${MYSQLDB_DATABASE}
      - DB_PORT=${MYSQLDB_DOCKER_PORT}
      # we dont need redis_url for now
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_DOCKER_PORT}
      - REDIS_PASS=${REDIS_PASS}
    stdin_open: true
    tty: true
    networks:
      - my-net
  cache:
    image: redis
    env_file:
      - ./.env
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASS=${REDIS_PASS}
    ports:
      - "${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}"
    volumes:
      - cache:/data
    restart: always
    networks:
      - my-net
    entrypoint: redis-server --appendonly yes
    # --requirepass ${REDIS_PASS}

networks:
  my-net:
volumes:
  db:
  cache:
    driver: local